### ISSUE TITLE
python error when using VIP+ servers

### ISSUE THREAD

**Issue by theeb** [0xdf223/PyHTBcli#3]
Hi,
I am getting this error whenever i switch to VIP+ servers where i can't list the servers

![pyHTBclie_error](https://user-images.githubusercontent.com/1061661/192110428-ede4e6a3-037a-4c46-8768-6f1974d9689b.png)

**Comment by 0xdf223** [comment]
Believe this is fixed in 0.0.7. Please let me know if it works for you!

**Comment by theeb** [comment]
Thank you for the prompt response. Its fixed.
